### ISSUE TITLE
Create a Release

### ISSUE THREAD

**Issue by simono** [dlh/youtube-dl-parallel#1]
Thanks for creating youtube-dl-parallel. I really like it and use it a lot!

Do you think it would be possible to create a Release to include youtube-dl-parallel in package managers like homebrew? That would be great.

Thanks.

**Comment by dlh** [comment]
Sure—I'll tag a release in the next few days.

About Homebrew: `youtube-dl-parallel` doesn't currently meet their notoriety requirements for GitHub projects, so it currently can't be packaged in their main repo.

**Comment by dlh** [comment]
Tagged and released [version 1.0.0](https://github.com/dlh/youtube-dl-parallel/releases/tag/1.0.0)

**Comment by simono** [comment]
Thanks, I'll try my luck and submit a PR to homebrew :-)

**Comment by simono** [comment]
Here's  a Repository with youtube-dl-parallel https://github.com/simono/homebrew-simono
